// frontend/src/components/AddHotel.tsx
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { hotelService } from '../services/HotelService';

interface FormData {
  name: string;
  description: string;
  price: number;
}

export default function AddHotel() {
  const navigate = useNavigate();
  const { register, handleSubmit } = useForm<FormData>();

  const onSubmit = async (data: FormData) => {
    try {
      await hotelService.createHotel(data);
      navigate('/');
    } catch (error) {
      console.error('Error adding hotel:', error);
    }
  };

  const cancel = () => {
    navigate('/');
  };

  return (
    <div className="container py-3">
      <div className="row justify-content-center">
        <div className="col-12 col-md-8 col-lg-6">
          <h2 className="text-center">Add Hotel</h2>
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="form-group mb-2">
              <label htmlFor="name">Name:</label>
              <input 
                {...register('name', { required: true })} 
                placeholder="Name" 
                className="form-control" 
                id="name" 
              />
            </div>
            <div className="form-group mb-2">
              <label htmlFor="description">Description:</label>
              <input 
                {...register('description', { required: true })} 
                placeholder="Description" 
                className="form-control" 
                id="description" 
              />
            </div>
            <div className="form-group mb-3">
              <label htmlFor="price">Price:</label>
              <input 
                type="number"
                step="0.01"
                {...register('price', { required: true, valueAsNumber: true })} 
                placeholder="Mean Room Price" 
                className="form-control" 
                id="price" 
              />
            </div>
            <button type="submit" className="btn btn-primary me-2">Add hotel</button>
            <button type="button" className="btn btn-secondary" onClick={cancel}>Cancel</button>
          </form>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/add-hotel/add-hotel.component.ts
import { Component, OnInit } from '@angular/core';
import { HotelService } from '../service/hotel.service';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-add-hotel',
  templateUrl: './add-hotel.component.html',
  styleUrls: ['./add-hotel.component.css']
})
export class AddHotelComponent implements OnInit {

  addForm: FormGroup;

  constructor(private formBuilder: FormBuilder, private router: Router, private hotelService: HotelService) {
    this.addForm = formBuilder.group({
      title: formBuilder.control('', Validators.required)
    });
  }

  ngOnInit() {
    this.addForm = this.formBuilder.group({
      id: [],
      name: ['', Validators.required],
      description: ['', Validators.required],
      price: ['', Validators.required]
    });
  }

  onSubmit() {
    this.hotelService.createHotel(this.addForm.value)
      .subscribe( data => {
        this.router.navigate(['list-hotel']);
      });
  }

}

<div class="col-md-12">
  <h2 class="text-center">Add Hotel</h2>
  <form [formGroup]="addForm" (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label for="name">Name:</label>
      <input formControlName="name" placeholder="Name" name="name" class="form-control" id="name">
    </div>

    <div class="form-group">
      <label for="description">Description:</label>
      <input formControlName="description" placeholder="Descriptions" name="description" class="form-control" id="description">
    </div>

    <div class="form-group mb-3">
      <label for="price">Price:</label>
      <input formControlName="price" placeholder="Mean Room Price" name="price" class="form-control" id="price">
    </div>

    <button class="btn btn-primary">Add hotel</button>
    <button class="btn btn-secondary cancel" type="button" (click)="cancel()">Cancel</button>
  </form>
</div>
