// frontend/src/components/DetailHotel.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { hotelService } from '../services/HotelService';
import type { Hotel } from '../models/Hotel';

export default function DetailHotel() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [hotel, setHotel] = useState<Hotel | null>(null);

  useEffect(() => {
    if (!id) {
      alert('Invalid action.');
      navigate('/');
      return;
    }

    const fetchDetail = async () => {
      try {
        const data = await hotelService.getHotelById(Number(id));
        setHotel(data);
      } catch (error) {
        console.error('Error fetching hotel:', error);
        alert('Error fetching hotel');
        navigate('/');
      }
    };

    fetchDetail();
  }, [id, navigate]);

  const list = () => {
    navigate('/');
  };

  if (!hotel) {
    return <div className="text-center py-5">Loading...</div>;
  }

  return (
    <div className="container py-3">
      <h2 className="text-center">Hotel Details</h2>
      <hr />
      <div className="row justify-content-center">
        <div className="col-12 col-md-8 col-lg-6">
          <div className="mb-2">
            <label><b>Name: </b></label> {hotel.name}
          </div>
          <div className="mb-2">
            <label><b>Description: </b></label> {hotel.description}
          </div>
          <div className="mb-2">
            <label><b>Mean Room Price: </b></label> {new Intl.NumberFormat('en-US', { style: 'currency', currency: 'EUR' }).format(hotel.price)}
          </div>
          <button onClick={list} className="btn btn-primary mt-3">Back to Hotels List</button>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/detail-hotel/detail-hotel.component.ts
import { Component, OnInit } from '@angular/core';
import { Hotel } from '../model/hotel.model';
import { ActivatedRoute, Router } from '@angular/router';
import { HotelService } from '../service/hotel.service';

@Component({
  selector: 'app-hotel-detail',
  templateUrl: './detail-hotel.component.html',
  styleUrls: ['./detail-hotel.component.css']
})
export class DetailHotelComponent implements OnInit {

  id: string;
  hotel: any;

  constructor(private route: ActivatedRoute, private router: Router, private hotelService: HotelService) { }

  ngOnInit() {
    this.hotel = new Hotel();
    const hotelId = +localStorage.getItem('hotelDetailId');
    if (!hotelId) {
      alert('Invalid action.');
      this.router.navigate(['list-hotel']);
      return;
    }

    this.hotelService.getHotelById(hotelId)
      .subscribe(data => {
        console.log(data);
        this.hotel = data;
      }, error => console.log(error));
  }

  list(){
    this.router.navigate(['list-hotel']);
  }

}


<div class="container py-3">
  <h2 class="text-center">Hotel Details</h2>
  <hr/>
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="mb-2">
        <label><b>Name: </b></label> {{hotel.name}}
      </div>
      <div class="mb-2">
        <label><b>Description: </b></label> {{hotel.description}}
      </div>
      <div class="mb-2">
        <label><b>Mean Room Price: </b></label> {{hotel.price | number | currency:'EUR'}}
      </div>
      <button (click)="list()" class="btn btn-primary mt-3">Back to Hotels List</button>
    </div>
  </div>
</div>
