// frontend/src/components/EditHotel.tsx
import { useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { hotelService } from '../services/HotelService';
import type { Hotel } from '../models/Hotel';

export default function EditHotel() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { register, handleSubmit, reset } = useForm<Hotel>();

  useEffect(() => {
    if (!id) {
      alert('Invalid action.');
      navigate('/');
      return;
    }

    const fetchHotel = async () => {
      try {
        const hotel = await hotelService.getHotelById(Number(id));
        reset(hotel);
      } catch (error) {
        console.error('Error fetching hotel:', error);
        alert('Error fetching hotel');
        navigate('/');
      }
    };

    fetchHotel();
  }, [id, navigate, reset]);

  const onSubmit = async (data: Hotel) => {
    try {
      await hotelService.updateHotel(data);
      navigate('/');
    } catch (error) {
      console.error('Error updating hotel:', error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      alert(errorMessage);
    }
  };

  const cancel = () => {
    navigate('/');
  };

  return (
    <div className="container py-3">
      <div className="row justify-content-center">
        <div className="col-12 col-md-8 col-lg-6">
          <h2 className="text-center">Edit Hotel</h2>
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="form-group mb-2">
              <label htmlFor="name">Name:</label>
              <input 
                {...register('name', { required: true })} 
                placeholder="Name" 
                className="form-control" 
                id="name" 
              />
            </div>
            <div className="form-group mb-2">
              <label htmlFor="description">Description:</label>
              <input 
                {...register('description', { required: true })} 
                placeholder="Description" 
                className="form-control" 
                id="description" 
              />
            </div>
            <div className="form-group mb-3">
              <label htmlFor="price">Price:</label>
              <input 
                type="number"
                step="0.01"
                {...register('price', { required: true, valueAsNumber: true })} 
                placeholder="Mean Room Price" 
                className="form-control" 
                id="price" 
              />
            </div>
            <button type="submit" className="btn btn-primary me-2">Update</button>
            <button type="button" className="btn btn-secondary" onClick={cancel}>Cancel</button>
          </form>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/edit-hotel/edit-hotel.component.ts
import { Component, OnInit } from '@angular/core';
import { Hotel } from '../model/hotel.model';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HotelService } from '../service/hotel.service';
import { first } from 'rxjs/operators';

@Component({
  selector: 'app-edit-hotel',
  templateUrl: './edit-hotel.component.html',
  styleUrls: ['./edit-hotel.component.css']
})
export class EditHotelComponent implements OnInit {

  hotel: Hotel;
  editForm: FormGroup;

  constructor(private formBuilder: FormBuilder, private router: Router, private hotelService: HotelService) { }

  ngOnInit() {
    const hotelId = +localStorage.getItem('editHotelId');
    if (!hotelId) {
      alert('Invalid action.');
      this.router.navigate(['list-hotel']);
      return;
    }
    this.editForm = this.formBuilder.group({
      id: [],
      name: ['', Validators.required],
      description: ['', Validators.required],
      price: ['', Validators.required]
    });
    this.hotelService.getHotelById(hotelId)
      .subscribe(data => {
        this.editForm.setValue(data);
      });
  }

  onSubmit() {
    this.hotelService.updateHotel(this.editForm.value)
      .pipe(first())
      .subscribe(
        data => {
          this.router.navigate(['list-hotel']);
        },
        error => {
          alert(error);
        });
  }

}


<div class="container py-3">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <h2 class="text-center">Edit Hotel</h2>
      <form [formGroup]="editForm" (ngSubmit)="onSubmit()">
        <div class="form-group mb-2">
          <label for="name">Name:</label>
          <input formControlName="name" placeholder="Name" name="name" class="form-control" id="name">
        </div>
        <div class="form-group mb-2">
          <label for="description">Description:</label>
          <input formControlName="description" placeholder="Descriptions" name="description" class="form-control" id="description">
        </div>
        <div class="form-group mb-3">
          <label for="price">Price:</label>
          <input formControlName="price" placeholder="Mean Room Price" name="price" class="form-control" id="price">
        </div>
        <button class="btn btn-primary me-2">Update</button>
        <button class="btn btn-secondary cancel" type="button" (click)="cancel()">Cancel</button>
      </form>
    </div>
  </div>
</div>
